
services:
  httpserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: ./cmd/httpserver
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  gqlserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: ./cmd/gqlserver
    ports:
      - "8081:8080"
    environment:
      - PORT=8080

  grpcserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: ./cmd/grpcserver
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
